name: ada
channels:
  - conda-forge
dependencies:
  - pythonocc-core
  - ifcopenshell
  - pip
  - pip:
      - gmsh
      - meshio
      - pandas
      - toolz
      - pyquaternion
      - lmfit
      - ccx2paraview
      - jupyterlab
      - pythreejs
      - pyparsing
      - plotly
      - kaleido


