name: ci-ada-fem

on:
  push:
    paths:
      - src/**
      - images/tests/**
      - conda/**
      - .github/workflows/ci-FEM.yml
      - Dockerfile
    branches:
    - main
    - dev
  pull_request:
    paths-ignore:
      - setup.py
    branches:
      - main

jobs:
  activate:
    if: |
      github.repository == 'krande/adapy' &&
      !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - run: echo ok go
  test-FEM:
    name: Test-FEM-analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - run: echo ${{ env.DATE }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%y%m%d')"
      - name: Build docker for FEM
        run: make dtest-b
      - name: Test & Create Verification Report
        run: make dtest-r
      - name: Upload Zip file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: temp/_dist/ADA-FEA-verification.docx
          asset_name: ADA-FEA-verification-${{steps.date.outputs.date}}.docx
          tag: "ADA-FEA-Verification-Report-${{steps.date.outputs.date}}"
          overwrite: true
          body: "Verification Report for ADAPY - ${{steps.date.outputs.date}}"
