name: ci-ada-fem

on:
  push:
    paths:
      - src/**
      - images/tests/**
      - conda/**
      - .github/workflows/ci-FEM.yml
    branches:
    - main
    - dev
  pull_request:
    paths-ignore:
      - setup.py
    branches:
      - main

jobs:
  activate:
    if: |
      github.repository == 'krande/adapy' &&
      !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - run: echo ok go
  docker-test:
    name: Test-FEM-analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - run: echo ${{ env.DATE }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%y%m%d')"
      - name: Build
        run: docker build -t ada/testing .
      - name: Create temp dir
        run: mkdir tmp
      - name: Test & Build Verification Report
        run: docker run --mount type=bind,source="$(pwd)/tmp",target=/home/tests/fem/temp ada/testing bash -c "pip install pytest pandas pydantic && cd /home/tests/fem && pytest && python build_verification_report.py"
      - name: Copy Verification Report from container
        run: cd tmp && ls
      - name: Upload Zip file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tmp/_dist/ADA-FEA-verification.docx
          asset_name: ADA-FEA-verification-${{steps.date.outputs.date}}.docx
          tag: "ADA-FEA-verification-${{steps.date.outputs.date}}"
          overwrite: true
          body: "Verification Report for ADAPY - ${{steps.date.outputs.date}}"