name: Experiment
on: [push]

jobs:
  debug:
    runs-on: ubuntu-latest
    container:
      image: krande/ada:base
      options: "--entrypoint /bin/bash"
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - run: conda install -c krande -c conda-forge paradoc
      - run: pip install . --no-cache-dir